name: Go Build and Release

on:
  push:
    tags:
      - '*.*.*' # Triggers only on version tags like 1.0.0

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build binaries
      run: |
        mkdir -p dist
        # Build the standard binary (no special build tags)
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/wsnet_go_${{ matrix.goos }}_${{ matrix.goarch }}

        # Build the Tailscale **server** variant (tag: tailscale)
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -tags tailscale -o dist/wsnet_go_tailscale_${{ matrix.goos }}_${{ matrix.goarch }}

        # Build the Tailscale **client** variant (tags: tailscale tailscaleclient)
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -tags "tailscale tailscaleclient" -o dist/wsnet_go_tailscale_client_${{ matrix.goos }}_${{ matrix.goarch }}

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: wsnet_go
        path: dist/

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Download binaries
      uses: actions/download-artifact@v4
      with:
        name: wsnet_go
        path: dist/

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
